# Generated by Django 4.0.6 on 2022-07-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='self_introduction',
        ),
    ]
