# Generated by Django 4.0.6 on 2022-07-27 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jenre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('over_view', models.TextField(max_length=1000)),
                ('jenre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenre.jenre')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
