# Generated by Django 4.0.6 on 2022-07-28 22:46

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventpics',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_eventpics_path),
        ),
    ]
