# Generated by Django 4.0.6 on 2022-07-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
